apis:
  service.controller.hue:
    name: Hue Controller
    prefix: service.controller.hue
    upstream_url: http://192.168.1.100:7007
    allow_cross_origin: true
    plugins:
      - name: retry
        enabled: true
        config:
          attempts: 3

  service.controller.infrared:
    name: Infrared Controller
    prefix: service.controller.infrared
    upstream_url: http://192.168.1.100:7008
    allow_cross_origin: true
    plugins:
      - name: retry
        enabled: true
        config:
          attempts: 3

  service.controller.plug:
    name: TP-Link Plug Controller
    prefix: service.controller.plug
    upstream_url: http://192.168.1.100:7009
    allow_cross_origin: true
    plugins:
      - name: retry
        enabled: true
        config:
          attempts: 3

  service.device-registry:
    name: Device Registry
    prefix: service.device-registry
    upstream_url: http://192.168.1.100:7001
    allow_cross_origin: true
    plugins:
      - name: retry
        enabled: true
        config:
          attempts: 3
